"""
MLflow Database Configuration

Sets up SQLite database backend for MLflow instead of file-based storage.
Provides better data management, querying, and portability.

Usage:
    python setup_mlflow_db.py              # Create and initialize database
    python setup_mlflow_db.py --migrate    # Migrate existing runs to database
"""

import os
import sqlite3
import shutil
from pathlib import Path
import mlflow
import argparse


class MLflowDatabaseSetup:
    """Setup and configure MLflow database backend."""
    
    def __init__(self, db_path: str = None):
        """
        Initialize database setup.
        
        Args:
            db_path: Path to SQLite database file (default: mlflow/mlflow.db)
        """
        self.project_root = Path(__file__).parent.parent
        self.mlflow_dir = Path(__file__).parent
        
        if db_path:
            self.db_path = Path(db_path)
        else:
            self.db_path = self.mlflow_dir / "mlflow.db"
        
        # Database URI for MLflow
        self.db_uri = f"sqlite:///{self.db_path.absolute()}"
        
        # Artifacts directory
        self.artifacts_dir = self.mlflow_dir / "mlartifacts"
        self.artifacts_dir.mkdir(exist_ok=True)
        
        print(f"Database path: {self.db_path}")
        print(f"Database URI: {self.db_uri}")
        print(f"Artifacts directory: {self.artifacts_dir}")
    
    def create_database(self):
        """Create the MLflow database if it doesn't exist."""
        if self.db_path.exists():
            print(f"[OK] Database already exists at {self.db_path}")
            return
        
        print(f"Creating database at {self.db_path}...")
        
        # Set the tracking URI to create the database
        mlflow.set_tracking_uri(self.db_uri)
        
        # Create a test experiment to initialize the database schema
        try:
            experiment_id = mlflow.create_experiment(
                "test_initialization",
                artifact_location=str(self.artifacts_dir / "test")
            )
            
            # Delete the test experiment
            mlflow.delete_experiment(experiment_id)
            
            print("[OK] Database created and initialized successfully")
        except Exception as e:
            print(f"[ERROR] Error creating database: {e}")
            raise
    
    def create_env_file(self):
        """Create .env file with MLflow configuration."""
        env_path = self.mlflow_dir / ".mlflow_config"
        
        config = f"""# MLflow Database Configuration
# Generated by setup_mlflow_db.py

# Tracking URI (database backend)
MLFLOW_TRACKING_URI={self.db_uri}

# Artifacts location
MLFLOW_ARTIFACT_ROOT={self.artifacts_dir.absolute()}

# To use this configuration:
# 1. Load these environment variables before running experiments
# 2. Or import and use mlflow_config.py in your scripts
"""
        
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(config)
        
        print(f"[OK] Configuration file created: {env_path}")
    
    def create_config_module(self):
        """Create Python module for MLflow configuration."""
        config_path = self.mlflow_dir / "mlflow_config.py"
        
        config_code = f'''"""
MLflow Configuration Module

Automatically configure MLflow to use SQLite database backend.
Import this module at the start of your experiment scripts.

Usage:
    from mlflow_config import configure_mlflow
    configure_mlflow()
"""

import mlflow
import os
from pathlib import Path


# Paths - using Path objects to avoid Windows backslash issues
MLFLOW_DIR = Path(__file__).parent
DB_PATH = MLFLOW_DIR / "mlflow.db"
ARTIFACTS_DIR = MLFLOW_DIR / "mlartifacts"

# Database URI - use as_posix() to convert to forward slashes
DB_URI = f"sqlite:///{{DB_PATH.as_posix()}}"


def configure_mlflow(verbose=True):
    """
    Configure MLflow with database backend.
    
    Args:
        verbose: If True, print configuration info
    """
    # Ensure artifacts directory exists
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    
    # Set tracking URI
    mlflow.set_tracking_uri(DB_URI)
    
    if verbose:
        print(f"[OK] MLflow configured with database backend")
        print(f"  Database: {{DB_PATH}}")
        print(f"  URI: {{DB_URI}}")


def get_tracking_uri():
    """Get the MLflow tracking URI."""
    return DB_URI


def get_artifacts_dir():
    """Get the artifacts directory."""
    return ARTIFACTS_DIR


# Auto-configure when imported
configure_mlflow(verbose=False)
'''
        
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write(config_code)
        
        print(f"[OK] Configuration module created: {config_path}")
    
    def show_usage_instructions(self):
        """Display usage instructions."""
        print("\n" + "="*70)
        print("MLflow Database Setup Complete!")
        print("="*70)
        
        print("\nHow to use the database backend:\n")
        
        print("Option 1: Import configuration module (RECOMMENDED)")
        print("-" * 50)
        print("Add to the top of your experiment scripts:")
        print("    from mlflow_config import configure_mlflow")
        print("    configure_mlflow()")
        print()
        
        print("Option 2: Set environment variable")
        print("-" * 50)
        print("Before running experiments:")
        print(f"    set MLFLOW_TRACKING_URI={self.db_uri}")
        print()
        
        print("Option 3: Use tracking URI directly")
        print("-" * 50)
        print("In your code:")
        print(f"    mlflow.set_tracking_uri('{self.db_uri}')")
        print()
        
        print("Starting MLflow UI:")
        print("-" * 50)
        print(f"    mlflow ui --backend-store-uri {self.db_uri}")
        print(f"    # Or from mlflow directory:")
        print(f"    cd {self.mlflow_dir}")
        print(f"    mlflow ui --backend-store-uri sqlite:///mlflow.db")
        print()
        
        print("Benefits of database backend:")
        print("-" * 50)
        print("  - Better data integrity and consistency")
        print("  - Easier querying and analysis")
        print("  - Single file for all experiment metadata")
        print("  - Better concurrent access handling")
        print("  - Easier backup and versioning")
        print()
    
    def migrate_existing_runs(self):
        """Migrate existing file-based runs to database."""
        mlruns_dir = self.mlflow_dir.parent / "mlruns"
        
        if not mlruns_dir.exists():
            print("[INFO] No existing mlruns directory found, nothing to migrate")
            return
        
        print(f"\n[WARNING] Migration from {mlruns_dir} to database")
        print("This will copy existing experiment runs to the database")
        
        # This is a simplified migration - for production, use MLflow's built-in tools
        print("\n[INFO] For complete migration, use:")
        print(f"  mlflow experiments csv -o experiments.csv")
        print(f"  # Then use MLflow's import functionality")
        
        print("\n[INFO] Alternatively, you can:")
        print("  1. Keep existing mlruns/ for historical reference")
        print("  2. Start fresh with new database")
        print("  3. Re-run important experiments to populate database")


def main():
    """Main setup function."""
    parser = argparse.ArgumentParser(description="Setup MLflow database backend")
    parser.add_argument('--db-path', type=str, help='Custom database path')
    parser.add_argument('--migrate', action='store_true', 
                       help='Migrate existing runs from mlruns/')
    args = parser.parse_args()
    
    print("="*70)
    print("MLflow Database Setup")
    print("="*70)
    print()
    
    setup = MLflowDatabaseSetup(db_path=args.db_path)
    
    # Create database
    setup.create_database()
    
    # Create configuration files
    setup.create_env_file()
    setup.create_config_module()
    
    # Show usage instructions
    setup.show_usage_instructions()
    
    # Migrate if requested
    if args.migrate:
        setup.migrate_existing_runs()
    
    print("\n[OK] Setup complete!")


if __name__ == "__main__":
    main()
